config/routes.rb
Rails.application.routes.draw do
  
  #root to: 'news#index'
  get 'news/index'

  #get 'news/index'
  resources :news
  resources :monitorings
  get 'sessions/new'

  resources :users
  root 'static_pages#home'
  
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get 'static_pages/home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'monitorings#index'
  delete '/logout',  to: 'sessions#destroy'
  get   '/monitorings',   to: 'monitorings#new'
  post 'monitorings', to: 'monitorings#create'
 
end

app/models/monitoring.rb
class Monitoring < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                      BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/monitorings_controller.rb
class MonitoringsController < ApplicationController
  before_action :set_monitoring, only: [:show, :edit, :update, :destroy]

  # GET /monitorings
  # GET /monitorings.json
  def index
    @monitorings = Monitoring.all
  end

  # GET /monitorings/1
  # GET /monitorings/1.json
  def show
  end

  # GET /monitorings/new
  def new
    @monitoring = Monitoring.new
  end

  # GET /monitorings/1/edit
  def edit
  end

  # POST /monitorings
  # POST /monitorings.json
  def create
    @monitoring = Monitoring.new(monitoring_params)

    respond_to do |format|
      if @monitoring.save
        format.html { redirect_to @monitoring, notice: 'Monitoring was successfully created.' }
        format.json { render :show, status: :created, location: @monitoring }
      else
        format.html { render :new }
        format.json { render json: @monitoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monitorings/1
  # PATCH/PUT /monitorings/1.json
  def update
    respond_to do |format|
      if @monitoring.update(monitoring_params)
        format.html { redirect_to @monitoring, notice: 'Monitoring was successfully updated.' }
        format.json { render :show, status: :ok, location: @monitoring }
      else
        format.html { render :edit }
        format.json { render json: @monitoring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monitorings/1
  # DELETE /monitorings/1.json
  def destroy
    @monitoring.destroy
    respond_to do |format|
      format.html { redirect_to monitorings_url, notice: 'Monitoring was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monitoring
      @monitoring = Monitoring.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monitoring_params
      params.require(:monitoring).permit(:local, :description)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @results = Google::Search::News.new(query: "Antartida")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the BiPOLAR Project"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monitorings_helper.rb
module MonitoringsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://bi-polar.herokuapp.com/">BiPOLAR PROJECT</a>
    by Luciano Trigueiro
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><a href="https://youtu.be/opYSUbjb_wU">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "BiPOLAR PROJECT", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Monitoring", monitorings_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | BiPOLAR PROJECT</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/monitorings/_form.html.erb
<%= form_for(@monitoring) do |f| %>
  <% if @monitoring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monitoring.errors.count, "error") %> prohibited this monitoring from being saved:</h2>

      <ul>
      <% @monitoring.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :local %><br>
    <%= f.text_field :local %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monitorings/edit.html.erb
<h1>Editing Monitoring</h1>

<%= render 'form' %>

<%= #link_to 'Show', @monitoring %> |
<%= #link_to 'Back', monitorings_path %>

app/views/monitorings/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading" id="painel_list"><div class="text-center"><h1>Listing Monitorings</h1></div></div>
    <div id="painel_body" class="paine-body">
      <table class="table table-hover">
            <thead>
              <tr>
                <th>
                   <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                     Local
                </th>
                <th>
                   <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>
                   Description
                </th>
                <th colspan="7"></th>
              </tr>
            </thead>
          
      
            <tbody>
              <% @monitorings.each do |monitoring| %>
                <tr>
                  <td><%= monitoring.local %></td>
                  <td><%= monitoring.description %></td>
                  
                </tr>
              <% end %>
            </tbody>
      </table>
    </div>
  </div>
</div>
<br>

app/views/monitorings/new.html.erb
<h1>New Monitoring</h1>

<%= render 'form' %>

<%= link_to 'Back', monitorings_path %>

app/views/monitorings/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <div class="col-md-2">
  <strong>Local:</strong>
  <%= @monitoring.local %>
  </div>
</p>

<p>
  <div class="col-md-2">    
  <strong>Description:</strong>
  <%= @monitoring.description %>
  </div>
</p>
<div class="text-center" id="buttons_show">
        <div class="row">
          <div class="col-md-6">
            <div class="pull-right">
              <div class="text-center"> <%= link_to 'Edit', edit_monitoring_path(@monitoring), {:style=>'color:black;', :class => "btn btn-default"} %> </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="pull-left">
              <div class="text-center"> <%= link_to 'Back', monitorings_path,  {:style=>'color:black;', :class => "btn btn-default"} %> </div>
            </div>
          </div>
        </div>
      </div>
      
  </div>
</div>

app/views/news/index.html.erb
<ul>
    <% @results.each do |result| %>
        <li>
            <p><%= link_to result.title, result.uri, target: 'blank' %></p>
            <p><%= simple_format result.content %></p>
        </li>
    <% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | BiPOLAR PROJECT</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      The Bipolar System is a tool for analyzing and providing information to researchers and inquirers about the spacial and temporal changes in Arctic and Antarctic ice. Through these analyzes, predict, evaluate, measure and report the damages that can be caused by activities at these poles. Provides an intuitive and efficient way for users to be informed and cautious on this subject. Using the tool, the user - in general, researcher or stakeholders - will be able to keep abreast of climate change, track progress / returns in recent years, interact with the most critical and affected areas.
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | BiPOLAR PROJECT</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>
      Get help on the BiPOLAR PROJECT at the
      <a href="https://bi-polar.herokuapp.com/static_pages/help"> help 
      section</a>.
      Or send an email to: contact@bipolarproject.com 
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center">
  <h1>FEEL IT NOW, PREDICT THE AFTER</h1>

  <h3>NEW EVENTS!</h3>

  <%= link_to "Sign up now!", signup_path , class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>